### PR TITLE
Preserved from properties when package is from git

### PR DESCRIPTION
**Pull request by tapayne88**

### CODE REVIEW

**Comment by glenjamin** [comment]
Could do with updating the fixtures as well

**Comment by glenjamin** [comment]
Released as `1.3.0`

**Comment by evocateur** [comment]
`npm` 2.x has an annoying habit of replacing these git dependency `"from"` keys with the `"resolved"` values on a subsequent `npm shrinkwrap`.

First run:

``` json
{
  "name": "git",
  "version": "1.0.0",
  "dependencies": {
    "async": {
      "version": "1.4.2",
      "from": "caolan/async#v1.4.2",
      "resolved": "git://github.com/caolan/async.git#92f78aebad222d60c13e4299c0e723f2fe2d6611"
    }
  }
}
```

Second run:

``` json
{
  "name": "git",
  "version": "1.0.0",
  "dependencies": {
    "async": {
      "version": "1.4.2",
      "from": "git://github.com/caolan/async.git#92f78aebad222d60c13e4299c0e723f2fe2d6611",
      "resolved": "git://github.com/caolan/async.git#92f78aebad222d60c13e4299c0e723f2fe2d6611"
    }
  }
}
```

The trivial example begs the question, "why u run twice with no changes?!", but just imagine another dependency needs updating. Running `shonkwrap` after `npm i -S other-dep` experiences the same problem, which is rather more egregious since the changes to the shrinkwrap should not normally encompass an unrelated git dep sibling.

(I might have spent the last two hours with this draft open working on a fancy fix)

**Comment by glenjamin** [comment]
Ouch, this sounds complicated.

I've never seen it happen before either - possibly because until recently we left out the from field. It was added back in for npm3 support.

Perhaps we could version detect and only include `from` for git under npm3?

**Comment by evocateur** [comment]
Actually, I'm remarkably close to fixing this with some judicious pre- and post-shrinkwrap traversal of the dependencies. I converted the bash script into an executable Node script so I could require npm packages like `traverse`, `load-json-file`, and `spawn-sync` (polyfills older Nodes with `child_process.spawnSync`), and it's quite a bit more robust.

I'll be sure to run it with npm 3 before I create the pull request. (I'm staying on npm 2 as a daily driver for the time being, as v3 is painfully slow in my experience)

**Comment by glenjamin** [comment]
For such a radical change I think you might be better off forking into an entirely new project!

I'll happily link to it from the README of this one

**Comment by evocateur** [comment]
Fair enough! I really do appreciate the work you've put into this tool as-is, though. I would have otherwise been driven mad by shrinkwrap shenanigans.

**Comment by evocateur** [comment]
@glenjamin I ended up publishing [shrinkwarp](https://github.com/evocateur/shrinkwarp), which for now is only guaranteed to work on npm 2 (and 1, heh, but who uses that?). There's a bug in npm 3's handling of git dependencies that is blocking full forward compatibility.

Thanks again for providing the original implementation!

**Comment by glenjamin** [comment]
@evocateur Have added a link to you in 91c303c4145892ac9ece42375664192d46e7b67b

**Comment by evocateur** [comment]
Thanks!

**Pull request merged**
